---
- name: install apt-transport-https and cert
  become: yes
  become_method: sudo
  apt: name={{item}} update_cache=yes state=latest
  with_items:
  - apt-transport-https
  - ca-certificates

- name: add keys
  become: yes
  become_method: sudo
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: add apt_repository
  become: yes
  become_method: sudo
  apt_repository: repo="deb https://apt.dockerproject.org/repo debian-jessie main"

- name: add docker-engine
  become: yes
  become_method: sudo
  apt: name=docker-engine update_cache=yes state=latest

- name: start docker service
  become: yes
  become_method: sudo
  service: name=docker state=started

