---
- hosts: localhost
  connection: local
  gather_facts: false
  # Definition of EC2 instances inspired by https://github.com/chrismeyersfsu/playbook-ec2_properties.
  vars:
    ec2_instances:
      - name: "machine1"
        tags: {Name: demo1, foo1: bar, foo2: bar}
      - name: "machine2"
        tags: {Name: demo2, foo1: bar, foo2: bar}
  roles:
    - aws
